### ISSUE TITLE
Plaid deprecates public_key

### ISSUE THREAD

**Issue by ImJustToNy** [austinkregel/finance#34]
![image](https://user-images.githubusercontent.com/5730766/91992365-577b4480-ed34-11ea-94b7-26fc33a89d91.png)

**Comment by austinkregel** [comment]
Oooh! Good catch! I haven't seen that alert 😅

**Comment by bernhardh** [comment]
So that means, you cannot use this project right now, is that correct? Since I don't see a public_key in my plaid account, I can't add it and because of this, I can't setup `finance`. I get (of course) the error:

```
Vue warn]: Error in mounted hook: "Error: Missing Link parameter. Link requires a key or token to be provided."
```

Btw. it would be better, to not just throw this error in the developer console, but as an alert or toast or whatever.

**Comment by austinkregel** [comment]
I'm sorry guys 😞  I haven't had a chance yet to look into this further. It is on my to-do list for sure, but I've been struggling with home-networking issues which has largely consumed my focus 😅  I've ordered new hardware which should arrive today and let me re-focus on this project moving forward 😄 

@bernhardh My goal would be to more gracefully handle the Plaid errors that might happen with a fix coming near the end of the week. 😄

**Comment by austinkregel** [comment]
Small update, I've been able to update the linking in a local branch, but the requests through the api fail because it (previously) needed the public key.

Another night or two, and there will be a PR up 😄 I've only had an hour or two to work on this so far, but I'm working on it 🤘

**Comment by austinkregel** [comment]
Okay, so now that v2.0 has been released, please give that a try 😄 Link tokens should work as expected now 👍

**Comment by bernhardh** [comment]
Thanks. I updated it and can start the link process, but I found out, that none of my banks (Austrian and German banks) are supported by plaid. So I can't test it.

Thank you for your help!

**Comment by austinkregel** [comment]
@bernhardh Dang 😞 Do you know if there's an alternative to the Plaid api that could be used for your region? I wouldn't be opposed to expanding support if there's something similar! 😄
If not, that's okay! I really appreciate your interest in the project!

**Comment by bernhardh** [comment]
There are some, but non of them is free for personell use. 

- For example https://www.finapi.io/ but the cheapest plan is for 20€ (~23$) per month for <100 user. No single user option. 
- Or https://fintecsystems.com/en/pricing/ - the prices are even higher (149€ / month) and no free or affordable plan, but at least a sandbox option.
- Another option is https://www.saltedge.com/solutions_for_finapps but they have no prices on there website which normally means they are very expensive ;)
- https://tink.com/pricing/ - "0.35€ per user per month" sounds not too bad, but thats probably part of a bigger package with 100+ users (I am just guessing).

JFYI - here is a list (from 2018) of providers grouped by differnt countries https://nordigen.com/en/blog/list-banking-apis-country/
