### ISSUE TITLE
Docs and PHP >7.4

### ISSUE THREAD

**Issue by LocalHeroPro** [austinkregel/finance#35]
In docs we have:
```
### Requirements
  - MySql
  - PHP >7.4
  - Redis (for queues and caching)
```
So proper PHP version is 7.5 and greater?
Confiused.

**Comment by austinkregel** [comment]
Oh man! Whoops! 

It's mean to be for php `>=7.4` 🙂 I'll update this tonight!

**Comment by LocalHeroPro** [comment]
So how it's possible? Because announcements of Laravel 8.x have in requirements PHP >= 7.3.
That repo use Laravel 7.x and there we have PHP >= 7.2.5.
https://laravel.com/docs/7.x
https://laravel.com/docs/8.x

Did you check all packages, and you are in 100% sure all dependence will work on >=7.4?
Only asking.

**Comment by austinkregel** [comment]
@LocalHeroPro I'm absolutely positive PHP version >=7.4  will work 😄. The docker image that this project was developed on is based on PHP 7.4 https://github.com/austinkregel/finance/blob/main/docker/php/Dockerfile
