### ISSUE TITLE
Cannot see transactions

### ISSUE THREAD

**Issue by markwalet** [austinkregel/finance#41]
My list of transactions is always empty. While the `transactions.account_id` matches my account key.

What can cause this kind of problems?
![image](https://user-images.githubusercontent.com/11446771/94116417-51681780-fe4b-11ea-821f-2d3fbeb30cb0.png)

I'm running the app on a default forge server with php7.4 And a Redis cache (because file cache is not taggable)

**Comment by markwalet** [comment]
The frontends sends an axios request with the following get parameter: `?filter[account_id]=in:{accountIdA}`. But the backend doesn't recognize the `in:` part of this and forms the query like the following:  `SELECT * FROM transactions WHERE account_id LIKE ?`

**Comment by austinkregel** [comment]
🤔 Hmm. I currently don't have a problem with this. Were you able to hook up your bank account (or a test bank through the standbox)?

If so, are your accounts listed under your bank? (If not, please click the refresh button next to the bank name). The initial syncing of transactions isn't automatic just yet, though I really think it needs to be 😅 

I think I still have to finish up the documentation for the whole linking process 😅

**Comment by markwalet** [comment]
The database contains my transactiona. But the generated query that is used is wrong.

It generates like this: `SELECT * from transactions where account_id LIKE '%in:{code}%`.

While it should be `SELECT * FROM transactions WHERE account_id IN ("{code}")`

**Comment by austinkregel** [comment]
Honestly, I'm not sure why this would be happening :sweat_smile: . Throughout my testing this has worked just fine :thinking: 

Pulling down the main branch, recompiling my assets, and using a sandbox account things seem to load just fine for me with that query :thinking: 
![image](https://user-images.githubusercontent.com/5355937/94174992-04dd0600-fe64-11ea-87ed-619738cbfb32.png)

I'll try to dig into this further tonight to see if I can replicate this problem :smile:

**Comment by markwalet** [comment]
I see that your request looks the same as mine. But what kind of query does your api generate? I just `dd()` the builder's `->toSql()` method.

**Comment by austinkregel** [comment]
:thinking: I turned on the Laravel Debug Bar via an ENV var `DEBUGBAR_ENABLED=true` and found I was actually getting this ugly query
```sql
select * from `transactions` where (LOWER(`account_id`) LIKE '%in:5mvkrkmzqai1qm6rq543hwrpvwkkprizanmbp%' or LOWER(`account_id`) LIKE '%jdmj6jddojurwnjagepzhqrkmy4zkdtdvrq1z%' or LOWER(`account_id`) LIKE '%kw7vpvwxgnhbrkdoyww8tlkrwz5wrbiwezkqq%' or LOWER(`account_id`) LIKE '%lne6j6ng8ps5ybwvxqjeszj9po3w9xizeb8nm%' or LOWER(`account_id`) LIKE '%qylvmvy5nziqypd718eviv7rdkkvr4id1wklx%' or LOWER(`account_id`) LIKE '%kd1j6jdwg7unmnbo4eblilnjl9zajkivazbkr%' or LOWER(`account_id`) LIKE '%rnpv1vnxbmsq1pb6w4xniwdkpvrpkmilvzgpb%' or LOWER(`account_id`) LIKE '%zxkvvvxb3wuonjj5kvwwtzywl1gpwbio1xwmj%' or LOWER(`account_id`) LIKE '%bb4jajbn7btqk6vb7jmnsawnmp8xnqhwn3nx9%') order by `date` desc limit 14 offset 0``

There is definitely a bug here, as that's not what the query should look like, but the page still functions for me.

**Comment by austinkregel** [comment]
I imagine it's because I have multiple accounts :thinking: If you only have 1 account I can see how this doesn't work :disappointed: Thanks for pointing this out! I'll work on this bug soon.

**Comment by austinkregel** [comment]
Hey @markwalet! If you have a bit of time to test out my PR #44, it should fix the problem you were running into :smile: 

(If you don't have time that's cool too, I'm confident it fixes the bug :wink: )

**Comment by markwalet** [comment]
You were right! I first thought you were wrong but I think it was a cache problem :)
