### ISSUE TITLE
Api routes use web middleware

### ISSUE THREAD

**Issue by markwalet** [austinkregel/finance#42]
Maybe we can put the api routes in the `api.php` file, where they belong.

If we use [Laravel Sanctum](https://laravel.com/docs/8.x/sanctum), I don't think this will be a large refactor. You are already on Laravel 7 so we can just install this. Would you like me to give it a try?

**Comment by austinkregel** [comment]
I'm not opposed to moving the API routes into the API file :sweat_smile: It's been bugging me a lot that this is my only project that doesn't follow that pattern :sweat_smile: 

As for Laravel Sanctum, I did investigate it for the 4th revision of this app (this currently is my 5th remake of the project :sweat_smile:) and unfortunately I gave up trying to fit Sanctum into the app when I realized I'd have to re-write the Vue components that handle the login logic :sweat_smile: 

I like Sanctum as a product, I just don't think it's the right fit for this project :smile: I really appreciate the suggestion though :bow:
